global:
  scrape_interval: 1s
  evaluation_interval: 1s
  
scrape_configs:
  - job_name: 'web-app'
    static_configs:
      - targets: [ 'localhost:8080' ]
        metrics_path: '/metrics'
  
  - job_name: 'node-exporter'
      static_configs:
      - targets: [ 'localhost:9100' ]
        metrics_path: '/metrics'
  